default_settings: null
behaviors:
  BlackAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.1
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 1
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: match3
      memory: null
      goal_conditioning_type: none
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 3
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: none
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    max_steps: 10000000
    time_horizon: 32
    summary_freq: 50000
    threaded: false
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning: null
  WhiteAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.1
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 1
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: match3
      memory: null
      goal_conditioning_type: none
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 3
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: none
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    max_steps: 10000000
    time_horizon: 32
    summary_freq: 50000
    threaded: false
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning: null
env_settings:
  env_path: C:\Develop\dobutsu\Build\windows\RL.exe
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 100
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 720
  height: 480
  quality_level: 1
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters: null
checkpoint_settings:
  run_id: CSI_1
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: cpu
debug: false
